//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShopApp.Models
{
    using CakeShopApp.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail : BaseViewModel
    {
        private int _invoiceId;
        public int InvoiceId { get => _invoiceId; set { _invoiceId = value; OnPropertyChanged(); } }

        private int _productId;
        public int ProductId { get => _productId; set { _productId = value; OnPropertyChanged(); } }

        private int _amount;
        public int Amount { get => _amount; set { _amount = value; OnPropertyChanged(); } }

        private int _discount;
        public int Discount { get => _discount; set { _discount = value; OnPropertyChanged(); } }

        private int _giftAmount;
        public int GiftAmount { get => _giftAmount; set { _giftAmount = value; OnPropertyChanged(); } }


        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
