//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShopApp.Models
{
    using CakeShopApp.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }

        private int _id;
        public int Id { get => _id; set { _id = value; OnPropertyChanged(); } }

        private string _name;
        public string Name { get => _name; set { _name = value; OnPropertyChanged(); } }

        private string _phone;
        public string Phone { get => _phone; set { _phone = value; OnPropertyChanged(); } }

        private int _paymentMethod;
        public int PaymentMethod { get => _paymentMethod; set { _paymentMethod = value; OnPropertyChanged(); } }

        private System.DateTime _createdDate;
        public System.DateTime CreatedDate { get => _createdDate; set { _createdDate = value; OnPropertyChanged(); } }

        private string _status;
        public string Status { get => _status; set { _status = value; OnPropertyChanged(); } }

        private int _total;
        public int Total { get => _total; set { _total = value; OnPropertyChanged(); } }

        public virtual DeliveryPayment DeliveryPayment { get; set; }
        public virtual DirectPayment DirectPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
